"""
Django settings for alephium project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False' == 'True')

ALLOWED_HOSTS = [
    os.getenv("DJANGO_ALLOWED_HOST")
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'books'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'alephium.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alephium.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

WALLET_DIR = BASE_DIR / 'wallet'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': os.getenv('ORACLE_DB_NAME'),
        'USER': os.getenv('ORACLE_DB_USER'),
        'PASSWORD': os.getenv('ORACLE_DB_PASSWORD'),
        'HOST': '', #both managed by tns
        'PORT': '',
        'OPTIONS': {
            'config_dir': str(WALLET_DIR),
            'wallet_location': str(WALLET_DIR),
            'wallet_password': os.getenv('ORACLE_WALLET_PASSWORD'),
        },
    }
}

# media bucket configuration
# OCI OBJECT STORAGE 
OCI_NAMESPACE = os.getenv("OCI_NAMESPACE")
OCI_BUCKET_NAME = os.getenv("OCI_BUCKET_NAME")
OCI_REGION = os.getenv("OCI_REGION")
OCI_SECRET_KEY = os.getenv("OCI_CUSTOMER_SECRET_KEY")
OCI_ACCESS_KEY = os.getenv("OCI_CUSTOMER_ACCESS_KEY")
OCI_NAMESPACE = os.getenv("OCI_NAMESPACE")
OCI_BUCKET_ENDPOINT_URL = f"https://{OCI_NAMESPACE}.compat.objectstorage.{OCI_REGION}.oraclecloud.com"

# OCI doesnt suppot aws checksums, so we have to disable them
os.environ['AWS_REQUEST_CHECKSUM_CALCULATION'] = 'when_required'
os.environ['AWS_RESPONSE_CHECKSUM_VALIDATION'] = 'when_required'

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": OCI_ACCESS_KEY,
            "secret_key":  OCI_SECRET_KEY,
            "bucket_name": OCI_BUCKET_NAME,
            "region_name": OCI_REGION,
            "endpoint_url": OCI_BUCKET_ENDPOINT_URL
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# media uploaded by users (covers, authors, etc)
MEDIA_URL = f'/media/'
MEDIA_ROOT = BASE_DIR / "media"




# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
